### ISSUE TITLE
Config Server Example link broken 

### ISSUE THREAD

**Issue by Voyz** [artemrys/config-server#2]
https://github.com/artemrys/config-server-example

![image](https://user-images.githubusercontent.com/15874847/92437377-f8ed1500-f1d0-11ea-84d6-b48766736215.png)

Expected a repo that I could test live, like described in the readme.

**Comment by artemrys** [comment]
I am sorry, I did not see this issue.

I deleted that repo when was cleaning my Github.

`config-server-example` repo is a repo with 1 file like `dev.yml`. You can find contents of this file in this repo's README.
